//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int ID { get; set; }
        public string FIRTSNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<int> DEPT { get; set; }

    }
}
